### ISSUE TITLE
Crash on remote save - NoSQL Data step

### ISSUE THREAD

**Issue by DonPepone** [aws-samples/aws-mobile-android-notes-tutorial#11]
I'm getting an exception after the configuration of the provider to save the notes in the online NoSQL Db.
The provider is defined as described in the tutorial and declared in the AndroidManifest.xml file
        <provider
            android:name=".data.NotesContentProvider"
            android:authorities="com.amazonaws.mobile.samples.mynotes.provider"
            android:label="NotesProvider" />

java.lang.SecurityException: Failed to find provider null for user 0; expected to find a valid ContentProvider for this authority
at android.os.Parcel.readException(Parcel.java:1942)
at android.os.Parcel.readException(Parcel.java:1888)
at android.content.IContentService$Stub$Proxy.notifyChange(IContentService.java:801)
at android.content.ContentResolver.notifyChange(ContentResolver.java:2046)
at android.content.ContentResolver.notifyChange(ContentResolver.java:1997)
at android.content.ContentResolver.notifyChange(ContentResolver.java:1967)
at com.amazonaws.mobile.samples.mynotes.data.NotesContentProvider.notifyAllListeners(NotesContentProvider.java:291)
at com.amazonaws.mobile.samples.mynotes.data.NotesContentProvider.insert(NotesContentProvider.java:217)
at android.content.ContentProvider$Transport.insert(ContentProvider.java:267)
at android.content.ContentResolver.insert(ContentResolver.java:1539)
at android.content.AsyncQueryHandler$WorkerHandler.handleMessage(AsyncQueryHandler.java:96)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by adrianhall** [comment]
Can you post the code you created - specifically, the insert() method in the ContentProvider.  It should be cut-and-paste from the tutorial.

**Comment by adrianhall** [comment]
Closing issue as it we didn't get any response.
